# Generated by Django 3.2.5 on 2021-07-11 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='current_video',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coder.video'),
        ),
    ]
