# Generated by Django 3.2.5 on 2021-07-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_rename_comment_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
